### ISSUE TITLE
Migrate to Heroku

### ISSUE THREAD

**Issue by ozzieba** [blanksblanks/project-cookie#18]

**Comment by ozzieba** [comment]
I got a Heroku server working, but it looks like we'd need to pay for Mongo support, or go through the code and remove everything that uses it. Since we can all use 'localhost:3000' (#12), this is not really urgent/may not be necessary

**Comment by levbrie** [comment]
Using the MongoLab add-on for Heroku is free for sandbox accounts, although you may have to enter a credit card into Heroku in order to access it.  If you don't want to enter a credit card at all, I believe that you can sign up directly on MongoLab without entering one and just set your environment variables in production to connect to MongoLab directly. 

![screen shot 2015-02-26 at 11 34 15 am](https://cloud.githubusercontent.com/assets/1441307/6396317/b0807b7c-bdab-11e4-8c48-f079b77fa767.png)

**Comment by ozzieba** [comment]
I set up a Heroku server at http://project-cookie.herokuapp.com/ and made you all collaborators. That means you can git clone/pull/push directly to the app. I also set up a mongolab instance at ds049651.mongolab.com:49651/project-cookie, and added you as collaborators. Your usernames are UNIs, and your passwords are all the same as the database user's password, which you can get from Heroku using 'heroku config:pull'
The basic process for uploading to Heroku is explained well in the generator docs, renamed here to generator_README.
I have changed our app's Github API key registration to the Heroku address, and transferred ownership to the Github Organization project-ccokie, which you're all invited to join. That way you can modify the key if necessary.
Good luck tomorrow, let me know in the evening how it went.

**Comment by jzf2101** [comment]
@ozzieba can you close if you think everything is ready to go?
